import * as acorn from "acorn";
import { ToolError } from "../errors.ts";
import type { ToolDefinition } from "../types.ts";

/**
 * Turn whatever the model sent as an implementation into the body of
 * `async function execute(args, ctx) { ... }`, and prove it cannot escape that function.
 *
 * Models are asked for a body but often send the whole function, sometimes exported,
 * sometimes as `const execute = async (args, ctx) => {...}`. All of those are unwrapped with
 * a real parser rather than a regex, so a `}` inside a string, comment, template or regex
 * literal cannot confuse it.
 *
 * The body is never reformatted. Re-indenting would change the contents of multi-line
 * template literals; only leading and trailing whitespace, which is outside any token, is
 * removed.
 */

const PARSE_OPTIONS: acorn.Options = {
  ecmaVersion: "latest",
  sourceType: "module",
  allowReturnOutsideFunction: true,
  allowAwaitOutsideFunction: true,
  locations: true
};

const HEADER = "async function execute(args, ctx) {\n";
const FOOTER = "\n}\n";

const ESCAPE_MESSAGE =
  "execute_source must be a function body. It closes the function early or declares things outside it.";

/** @returns The function body, verbatim apart from surrounding whitespace. */
export function unwrapExecuteSource(source: unknown): string {
  const text = typeof source === "string" ? source.trim() : "";
  if (!text) throw new ToolError("invalid_source", "execute_source is empty.");

  const body = (extractWrappedBody(text) ?? text).trim();
  assertIsFunctionBody(body);
  return body;
}

/** Assemble the module that will be written to disk and imported by the worker. */
export function buildModuleSource({ name, description, parameters, executeSource }: ToolDefinition & { executeSource: string }): string {
  const definition = JSON.stringify({ name, description, parameters }, null, 2);
  return (
    `// Generated by toolhost. The SQLite store is the source of truth; edits here are overwritten.\n` +
    `export const definition = ${definition};\n\n` +
    `export ${HEADER}${executeSource}${FOOTER}`
  );
}

/**
 * The module must contain exactly two exports, `definition` and `execute`, and nothing else,
 * so importing it runs no code.
 */
export function assertModuleSource(moduleSource: string): void {
  const program = parseOrThrow(moduleSource, 0);
  const statements = program.body.filter((node) => node.type !== "EmptyStatement");
  const [first, second, ...rest] = statements;
  const ok =
    rest.length === 0 &&
    first?.type === "ExportNamedDeclaration" &&
    first.declaration?.type === "VariableDeclaration" &&
    first.declaration.declarations[0]?.id.type === "Identifier" &&
    first.declaration.declarations[0].id.name === "definition" &&
    second?.type === "ExportNamedDeclaration" &&
    second.declaration?.type === "FunctionDeclaration" &&
    second.declaration.id?.name === "execute" &&
    second.declaration.async === true;
  if (!ok) {
    throw new ToolError("invalid_source", "Generated module has an unexpected shape.");
  }
}

// -- internals ------------------------------------------------------------------------

function extractWrappedBody(text: string): string | null {
  let program: acorn.Program;
  try {
    program = acorn.parse(text, PARSE_OPTIONS);
  } catch {
    return null; // Not a complete program; treat as a body and let the body check explain.
  }
  const statements = program.body.filter((node) => node.type !== "EmptyStatement");
  if (statements.length !== 1) return null;

  const fn = functionNode(statements[0]!);
  if (!fn || fn.body.type !== "BlockStatement") return null;
  return text.slice(fn.body.start + 1, fn.body.end - 1);
}

type FunctionLike = acorn.FunctionDeclaration | acorn.AnonymousFunctionDeclaration | acorn.FunctionExpression | acorn.ArrowFunctionExpression;

/** Accepts `function execute`, `export function execute`, `export default function`, and `const execute = async (...) => {}`. */
function functionNode(node: acorn.Statement | acorn.ModuleDeclaration): FunctionLike | null {
  const inner = node.type === "ExportNamedDeclaration" || node.type === "ExportDefaultDeclaration" ? node.declaration : node;
  if (!inner) return null;
  if (inner.type === "FunctionDeclaration") {
    return inner.id == null || inner.id.name === "execute" ? inner : null;
  }
  if (inner.type === "VariableDeclaration" && inner.declarations.length === 1) {
    const { id, init } = inner.declarations[0]!;
    if (id.type !== "Identifier" || id.name !== "execute" || !init) return null;
    if (init.type === "ArrowFunctionExpression" || init.type === "FunctionExpression") return init;
  }
  return null;
}

function assertIsFunctionBody(body: string): void {
  let program: acorn.Program;
  try {
    program = parseOrThrow(HEADER + body + FOOTER, 1);
  } catch (error) {
    // A body that closes the function and opens another `execute` trips the redeclaration
    // check first; the escape message is the useful one.
    if (error instanceof ToolError && /'execute' has already been declared/.test(error.message)) {
      throw new ToolError("invalid_source", ESCAPE_MESSAGE);
    }
    throw error;
  }
  const statements = program.body.filter((node) => node.type !== "EmptyStatement");
  const only = statements[0];
  if (statements.length !== 1 || only?.type !== "FunctionDeclaration" || only.id.name !== "execute") {
    throw new ToolError("invalid_source", ESCAPE_MESSAGE);
  }
}

function parseOrThrow(source: string, lineOffset: number): acorn.Program {
  try {
    return acorn.parse(source, PARSE_OPTIONS);
  } catch (error) {
    const loc = (error as { loc?: { line: number; column: number } }).loc;
    const bodyLines = source.split("\n").length - (lineOffset ? 3 : 0); // header, footer, trailing newline
    let line = loc ? loc.line - lineOffset : undefined;
    let column = loc ? loc.column + 1 : undefined;
    let message = (error as Error).message.replace(/\s*\(\d+:\d+\)$/, "");
    // An error past the last body line means the body ended mid-expression; point at its end.
    if (line !== undefined && lineOffset && line > bodyLines) {
      line = bodyLines;
      column = undefined;
      message = "Unexpected end of execute_source (an unclosed brace, bracket or parenthesis?)";
    }
    const where = line === undefined ? "" : column === undefined ? ` (line ${line})` : ` (line ${line}, column ${column})`;
    throw new ToolError("invalid_source", `Syntax error in execute_source${where}: ${message}`, { line, column });
  }
}
