import * as acorn from "acorn";
import { ToolError } from "./errors.js";

/**
 * Turn whatever the model sent as an implementation into the body of
 * `async function execute(args, ctx) { ... }`, and prove it cannot escape that function.
 *
 * Models are asked for a body but often send the whole function, sometimes exported,
 * sometimes as `const execute = async (args, ctx) => {...}`. All of those are unwrapped
 * with a real parser rather than a regex, so a `}` inside a string, comment, template
 * or regex literal cannot confuse it.
 */

const PARSE_OPTIONS = {
  ecmaVersion: "latest",
  sourceType: "module",
  allowReturnOutsideFunction: true,
  allowAwaitOutsideFunction: true,
  locations: true
};

const HEADER = "async function execute(args, ctx) {\n";
const FOOTER = "\n}\n";

/**
 * @param {unknown} source
 * @returns {string} The function body, dedented.
 */
export function unwrapExecuteSource(source) {
  const text = typeof source === "string" ? source.trim() : "";
  if (!text) throw new ToolError("invalid_source", "execute_source is empty.");

  const wrappedBody = extractWrappedBody(text);
  const body = dedent(wrappedBody ?? text);
  assertIsFunctionBody(body);
  return body;
}

/**
 * Assemble the module that will be written to disk and imported by the worker.
 *
 * @param {{ name: string, description: string, parameters: object, executeSource: string }} tool
 */
export function buildModuleSource({ name, description, parameters, executeSource }) {
  const definition = JSON.stringify({ name, description, parameters }, null, 2);
  return (
    `// Generated by toolhost. The SQLite store is the source of truth; edits here are overwritten.\n` +
    `export const definition = ${definition};\n\n` +
    `export ${HEADER}${indent(executeSource)}${FOOTER}`
  );
}

/**
 * The module must contain exactly two exports: `definition` and `execute`.
 * The body is already checked in `unwrapExecuteSource`; this guards the assembled file.
 *
 * @param {string} moduleSource
 */
export function assertModuleSource(moduleSource) {
  const program = parseOrThrow(moduleSource, 0);
  const statements = program.body.filter((node) => node.type !== "EmptyStatement");
  const [first, second, ...rest] = statements;
  const ok =
    rest.length === 0 &&
    first?.type === "ExportNamedDeclaration" &&
    first.declaration?.type === "VariableDeclaration" &&
    first.declaration.declarations[0]?.id?.name === "definition" &&
    second?.type === "ExportNamedDeclaration" &&
    second.declaration?.type === "FunctionDeclaration" &&
    second.declaration.id?.name === "execute" &&
    second.declaration.async === true;
  if (!ok) {
    throw new ToolError("invalid_source", "Generated module has an unexpected shape.");
  }
}

// -- internals ------------------------------------------------------------------------

function extractWrappedBody(text) {
  let program;
  try {
    program = acorn.parse(text, PARSE_OPTIONS);
  } catch {
    return null; // Not a complete program; treat as a body and let the body check explain.
  }
  const statements = program.body.filter((node) => node.type !== "EmptyStatement");
  if (statements.length !== 1) return null;

  const fn = functionNode(statements[0]);
  if (!fn || fn.body.type !== "BlockStatement") return null;
  return text.slice(fn.body.start + 1, fn.body.end - 1);
}

/** Accepts `function execute`, `export function execute`, `export default function`, and `const execute = async (...) => {}`. */
function functionNode(node) {
  const inner =
    node.type === "ExportNamedDeclaration" || node.type === "ExportDefaultDeclaration"
      ? node.declaration
      : node;
  if (!inner) return null;
  if (inner.type === "FunctionDeclaration") {
    return inner.id == null || inner.id.name === "execute" ? inner : null;
  }
  if (inner.type === "VariableDeclaration" && inner.declarations.length === 1) {
    const { id, init } = inner.declarations[0];
    if (id.type !== "Identifier" || id.name !== "execute" || !init) return null;
    if (init.type === "ArrowFunctionExpression" || init.type === "FunctionExpression") return init;
  }
  return null;
}

function assertIsFunctionBody(body) {
  const program = parseOrThrow(HEADER + body + FOOTER, 1);
  const statements = program.body.filter((node) => node.type !== "EmptyStatement");
  const only = statements[0];
  if (statements.length !== 1 || only.type !== "FunctionDeclaration" || only.id.name !== "execute") {
    throw new ToolError(
      "invalid_source",
      "execute_source must be a function body. It closes the function early or declares things outside it."
    );
  }
}

function parseOrThrow(source, lineOffset) {
  try {
    return acorn.parse(source, PARSE_OPTIONS);
  } catch (error) {
    const line = error.loc ? error.loc.line - lineOffset : undefined;
    const column = error.loc ? error.loc.column + 1 : undefined;
    const where = line === undefined ? "" : ` (line ${line}, column ${column})`;
    throw new ToolError("invalid_source", `Syntax error in execute_source${where}: ${stripPosition(error.message)}`, {
      line,
      column
    });
  }
}

function stripPosition(message) {
  return message.replace(/\s*\(\d+:\d+\)$/, "");
}

function dedent(text) {
  const lines = text.replace(/^\s*\n/, "").trimEnd().split("\n");
  const indents = lines.filter((line) => line.trim()).map((line) => line.match(/^[ \t]*/)[0].length);
  const shared = indents.length ? Math.min(...indents) : 0;
  return lines.map((line) => line.slice(shared)).join("\n");
}

function indent(text) {
  return text
    .split("\n")
    .map((line) => (line ? `  ${line}` : line))
    .join("\n");
}
